// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Data;

#nullable disable

namespace Portfolio.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260929015125_InitialPostgreSQL")]
    partial class InitialPostgreSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Models.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("About");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Image = "/images/Image.png",
                            Title = "Sobre"
                        });
                });

            modelBuilder.Entity("Portfolio.Models.EducationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAcademic")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EducationItems");
                });

            modelBuilder.Entity("Portfolio.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Proficiency")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Languages", t =>
                        {
                            t.HasCheckConstraint("CK_Languages_Proficiency_Range", "\"Proficiency\" >= 0 AND \"Proficiency\" <= 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Português",
                            Order = 0,
                            Proficiency = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Inglês",
                            Order = 1,
                            Proficiency = 0
                        });
                });

            modelBuilder.Entity("Portfolio.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Portfolio.Models.ProjectTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyId");

                    b.HasIndex("ProjectId", "TechnologyId")
                        .IsUnique();

                    b.ToTable("ProjectTechnologies");
                });

            modelBuilder.Entity("Portfolio.Models.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CvUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GithubUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CvUrl = "#projetos",
                            Email = "alyssonsb.dev@gmail.com",
                            GithubUrl = "#",
                            LinkedInUrl = "#",
                            Name = "Alysson Serafim Brito",
                            ProfessionalTitle = "Desenvolvedor de Jogos e Softwares",
                            ProfileImage = "/images/Image.png"
                        });
                });

            modelBuilder.Entity("Portfolio.Models.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Design",
                            Icon = "/images/technologies/figma.png",
                            Name = "Figma",
                            Order = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Design",
                            Icon = "/images/technologies/canva.png",
                            Name = "Canva",
                            Order = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Design",
                            Icon = "/images/technologies/photoshop.png",
                            Name = "Adobe Photoshop",
                            Order = 2
                        },
                        new
                        {
                            Id = 4,
                            Category = "Design",
                            Icon = "/images/technologies/illustrator.png",
                            Name = "Adobe Illustrator",
                            Order = 3
                        },
                        new
                        {
                            Id = 5,
                            Category = "Design",
                            Icon = "/images/technologies/xd.png",
                            Name = "Adobe XD",
                            Order = 4
                        },
                        new
                        {
                            Id = 6,
                            Category = "Backend e Banco de Dados",
                            Icon = "/images/technologies/csharp.png",
                            Name = "C#",
                            Order = 5
                        },
                        new
                        {
                            Id = 7,
                            Category = "Backend e Banco de Dados",
                            Icon = "/images/technologies/dotnet.png",
                            Name = ".NET",
                            Order = 6
                        },
                        new
                        {
                            Id = 8,
                            Category = "Backend e Banco de Dados",
                            Icon = "/images/technologies/sql.png",
                            Name = "SQL",
                            Order = 7
                        },
                        new
                        {
                            Id = 9,
                            Category = "Front-End",
                            Icon = "/images/technologies/html.png",
                            Name = "HTML",
                            Order = 8
                        },
                        new
                        {
                            Id = 10,
                            Category = "Front-End",
                            Icon = "/images/technologies/css.png",
                            Name = "CSS",
                            Order = 9
                        },
                        new
                        {
                            Id = 11,
                            Category = "Front-End",
                            Icon = "/images/technologies/javascript.png",
                            Name = "JavaScript",
                            Order = 10
                        },
                        new
                        {
                            Id = 12,
                            Category = "Front-End",
                            Icon = "/images/technologies/blazor.png",
                            Name = "Blazor",
                            Order = 11
                        },
                        new
                        {
                            Id = 13,
                            Category = "DevOps e Desenvolvimento",
                            Icon = "/images/technologies/git.png",
                            Name = "Git",
                            Order = 12
                        },
                        new
                        {
                            Id = 14,
                            Category = "DevOps e Desenvolvimento",
                            Icon = "/images/technologies/github.png",
                            Name = "GitHub",
                            Order = 13
                        },
                        new
                        {
                            Id = 15,
                            Category = "DevOps e Desenvolvimento",
                            Icon = "/images/technologies/docker.png",
                            Name = "Docker",
                            Order = 14
                        },
                        new
                        {
                            Id = 16,
                            Category = "DevOps e Desenvolvimento",
                            Icon = "/images/technologies/unity.png",
                            Name = "Unity",
                            Order = 15
                        });
                });

            modelBuilder.Entity("Portfolio.Models.WorkExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkExperiences", t =>
                        {
                            t.HasCheckConstraint("CK_WorkExperiences_CurrentHasNoEndDate", "\"IsCurrent\" = FALSE OR \"EndDate\" IS NULL");
                        });
                });

            modelBuilder.Entity("Portfolio.Models.WorkExperienceTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TechnologyId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkExperienceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyId");

                    b.HasIndex("WorkExperienceId", "TechnologyId")
                        .IsUnique();

                    b.ToTable("WorkExperienceTechnologies");
                });

            modelBuilder.Entity("Portfolio.Models.ProjectTechnology", b =>
                {
                    b.HasOne("Portfolio.Models.Project", "Project")
                        .WithMany("ProjectTechnologies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Models.Technology", "Technology")
                        .WithMany("ProjectTechnologies")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("Portfolio.Models.WorkExperienceTechnology", b =>
                {
                    b.HasOne("Portfolio.Models.Technology", "Technology")
                        .WithMany("WorkExperienceTechnologies")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Models.WorkExperience", "WorkExperience")
                        .WithMany("WorkExperienceTechnologies")
                        .HasForeignKey("WorkExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technology");

                    b.Navigation("WorkExperience");
                });

            modelBuilder.Entity("Portfolio.Models.Project", b =>
                {
                    b.Navigation("ProjectTechnologies");
                });

            modelBuilder.Entity("Portfolio.Models.Technology", b =>
                {
                    b.Navigation("ProjectTechnologies");

                    b.Navigation("WorkExperienceTechnologies");
                });

            modelBuilder.Entity("Portfolio.Models.WorkExperience", b =>
                {
                    b.Navigation("WorkExperienceTechnologies");
                });
#pragma warning restore 612, 618
        }
    }
}
